In [ ]:
import pandas as pd

# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)

# pd.reset_option('display.max_rows')
# pd.reset_option('display.max_columns')

In [35]:
df = pd.read_csv('/Users/fikrimaulana/Downloads/hotel_bookings 2.csv')
df.head(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.0,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.0,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.5,0,0,Canceled,2015-04-22

In [36]:
df.shape[0]

119390

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

# Data Cleaning for Hotel Bookings

## 1. Kolom yang Dihapus
Beberapa kolom tidak relevan atau tidak digunakan dalam analisis ini, sehingga akan dihapus untuk menyederhanakan dataset:

- **arrival_date_week_number**: Kolom ini dihapus karena tanggal kedatangan sudah diketahui dari kolom lain.
- **distribution_channel**: Kolom ini dihapus karena `market_segment` memberikan detail yang lebih tentang user yang memesan.
- **previous_bookings_not_canceled**: Tidak digunakan dalam analisis.
- **booking_changes**: Tidak digunakan dalam analisis.
- **agent**: Kolom ini dihapus karena terlalu banyak nilai null.
- **company**: Dihapus karena terlalu banyak data null.
- **required_car_parking_spaces**: Tidak digunakan untuk analisis.
- **total_of_special_requests**: Tidak digunakan untuk analisis.
- **reservation_status_date**: Dihapus karena tanggal reservasi sudah dapat diketahui dari kolom lain seperti `arrival_date_year`, `arrival_date_month`, dan `arrival_date_day_of_month`.

## 2. Gabungkan Kolom `children` dan `babies`
Dikarenakan pemesanan hotel hanya melibatkan opsi dewasa dan anak-anak, maka kolom `children` dan `babies` akan digabung menjadi satu kolom baru dengan nama `children`. Nilai null pada kolom ini akan diisi dengan 0.

## 3. Hapus Baris Berdasarkan Kondisi
### Baris dengan `previous_cancellations` > 0
Baris dengan nilai pada kolom `previous_cancellations` lebih dari 0 akan dihapus untuk menghindari duplikasi data.

### Baris dengan `days_in_waiting_list` > 31
Kolom ini merepresentasikan lamanya waktu menunggu dalam daftar tunggu. Data yang menunjukkan waktu tunggu lebih dari satu bulan (> 31 hari) akan dihapus karena dianggap tidak realistis.

## 4. Hapus Baris Null pada Kolom `country`
Beberapa baris pada kolom `country` memiliki nilai null. Karena jumlahnya sedikit, baris ini akan dihapus karena tidak terlalu mempengaruhi analisis secara keseluruhan.

---

Langkah-langkah pembersihan data ini akan menghasilkan dataset yang lebih rapi dan relevan untuk analisis lebih lanjut.

In [38]:
kolom_dihapus = ['arrival_date_week_number', 'distribution_channel', 'previous_bookings_not_canceled', 'booking_changes',
                 'agent', 'company', 'required_car_parking_spaces', 'total_of_special_requests', 'reservation_status_date']
df.drop(columns=kolom_dihapus, inplace=True, errors='ignore')
print("Setelah menghapus kolom tidak relevan:")
display(df.head(10))

Setelah menghapus kolom tidak relevan:

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,market_segment,is_repeated_guest,previous_cancellations,reserved_room_type,assigned_room_type,deposit_type,days_in_waiting_list,customer_type,adr,reservation_status
0,Resort Hotel,0,342,2015,July,1,0,0,2,0.0,...,Direct,0,0,C,C,No Deposit,0,Transient,0.0,Check-Out
1,Resort Hotel,0,737,2015,July,1,0,0,2,0.0,...,Direct,0,0,C,C,No Deposit,0,Transient,0.0,Check-Out
2,Resort Hotel,0,7,2015,July,1,0,1,1,0.0,...,Direct,0,0,A,C,No Deposit,0,Transient,75.0,Check-Out
3,Resort Hotel,0,13,2015,July,1,0,1,1,0.0,...,Corporate,0,0,A,A,No Deposit,0,Transient,75.0,Check-Out
4,Resort Hotel,0,14,2015,July,1,0,2,2,0.0,...,Online TA,0,0,A,A,No Deposit,0,Transient,98.0,Check-Out
5,Resort Hotel,0,14,2015,July,1,0,2,2,0.0,...,Online TA,0,0,A,A,No Deposit,0,Transient,98.0,Check-Out
6,Resort Hotel,0,0,2015,July,1,0,2,2,0.0,...,Direct,0,0,C,C,No Deposit,0,Transient,107.0,Check-Out
7,Resort Hotel,0,9,2015,July,1,0,2,2,0.0,...,Direct,0,0,C,C,No Deposit,0,Transient,103.0,Check-Out
8,Resort Hotel,1,85,2015,July,1,0,3,2,0.0,...,Online TA,0,0,A,A,No Deposit,0,Transient,82.0,Canceled
9,Resort Hotel,1,75,2015,July,1,0,3,2,0.0,...,Offline TA/TO,0,0,D,D,No Deposit,0,Transient,105.5,Canceled

In [39]:
df['children'] = df[['children', 'babies']].fillna(0).sum(axis=1).astype(int)
df.drop(columns='babies', inplace=True)
display(df.head(10))

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,market_segment,is_repeated_guest,previous_cancellations,reserved_room_type,assigned_room_type,deposit_type,days_in_waiting_list,customer_type,adr,reservation_status
0,Resort Hotel,0,342,2015,July,1,0,0,2,0,...,Direct,0,0,C,C,No Deposit,0,Transient,0.0,Check-Out
1,Resort Hotel,0,737,2015,July,1,0,0,2,0,...,Direct,0,0,C,C,No Deposit,0,Transient,0.0,Check-Out
2,Resort Hotel,0,7,2015,July,1,0,1,1,0,...,Direct,0,0,A,C,No Deposit,0,Transient,75.0,Check-Out
3,Resort Hotel,0,13,2015,July,1,0,1,1,0,...,Corporate,0,0,A,A,No Deposit,0,Transient,75.0,Check-Out
4,Resort Hotel,0,14,2015,July,1,0,2,2,0,...,Online TA,0,0,A,A,No Deposit,0,Transient,98.0,Check-Out
5,Resort Hotel,0,14,2015,July,1,0,2,2,0,...,Online TA,0,0,A,A,No Deposit,0,Transient,98.0,Check-Out
6,Resort Hotel,0,0,2015,July,1,0,2,2,0,...,Direct,0,0,C,C,No Deposit,0,Transient,107.0,Check-Out
7,Resort Hotel,0,9,2015,July,1,0,2,2,0,...,Direct,0,0,C,C,No Deposit,0,Transient,103.0,Check-Out
8,Resort Hotel,1,85,2015,July,1,0,3,2,0,...,Online TA,0,0,A,A,No Deposit,0,Transient,82.0,Canceled
9,Resort Hotel,1,75,2015,July,1,0,3,2,0,...,Offline TA/TO,0,0,D,D,No Deposit,0,Transient,105.5,Canceled

In [40]:
df = df[df['previous_cancellations'] == 0]
display(df.head(10))

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,market_segment,is_repeated_guest,previous_cancellations,reserved_room_type,assigned_room_type,deposit_type,days_in_waiting_list,customer_type,adr,reservation_status
0,Resort Hotel,0,342,2015,July,1,0,0,2,0,...,Direct,0,0,C,C,No Deposit,0,Transient,0.0,Check-Out
1,Resort Hotel,0,737,2015,July,1,0,0,2,0,...,Direct,0,0,C,C,No Deposit,0,Transient,0.0,Check-Out
2,Resort Hotel,0,7,2015,July,1,0,1,1,0,...,Direct,0,0,A,C,No Deposit,0,Transient,75.0,Check-Out
3,Resort Hotel,0,13,2015,July,1,0,1,1,0,...,Corporate,0,0,A,A,No Deposit,0,Transient,75.0,Check-Out
4,Resort Hotel,0,14,2015,July,1,0,2,2,0,...,Online TA,0,0,A,A,No Deposit,0,Transient,98.0,Check-Out
5,Resort Hotel,0,14,2015,July,1,0,2,2,0,...,Online TA,0,0,A,A,No Deposit,0,Transient,98.0,Check-Out
6,Resort Hotel,0,0,2015,July,1,0,2,2,0,...,Direct,0,0,C,C,No Deposit,0,Transient,107.0,Check-Out
7,Resort Hotel,0,9,2015,July,1,0,2,2,0,...,Direct,0,0,C,C,No Deposit,0,Transient,103.0,Check-Out
8,Resort Hotel,1,85,2015,July,1,0,3,2,0,...,Online TA,0,0,A,A,No Deposit,0,Transient,82.0,Canceled
9,Resort Hotel,1,75,2015,July,1,0,3,2,0,...,Offline TA/TO,0,0,D,D,No Deposit,0,Transient,105.5,Canceled

In [41]:
df = df[df['days_in_waiting_list'] <= 31]
display(df.head(10))

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,market_segment,is_repeated_guest,previous_cancellations,reserved_room_type,assigned_room_type,deposit_type,days_in_waiting_list,customer_type,adr,reservation_status
0,Resort Hotel,0,342,2015,July,1,0,0,2,0,...,Direct,0,0,C,C,No Deposit,0,Transient,0.0,Check-Out
1,Resort Hotel,0,737,2015,July,1,0,0,2,0,...,Direct,0,0,C,C,No Deposit,0,Transient,0.0,Check-Out
2,Resort Hotel,0,7,2015,July,1,0,1,1,0,...,Direct,0,0,A,C,No Deposit,0,Transient,75.0,Check-Out
3,Resort Hotel,0,13,2015,July,1,0,1,1,0,...,Corporate,0,0,A,A,No Deposit,0,Transient,75.0,Check-Out
4,Resort Hotel,0,14,2015,July,1,0,2,2,0,...,Online TA,0,0,A,A,No Deposit,0,Transient,98.0,Check-Out
5,Resort Hotel,0,14,2015,July,1,0,2,2,0,...,Online TA,0,0,A,A,No Deposit,0,Transient,98.0,Check-Out
6,Resort Hotel,0,0,2015,July,1,0,2,2,0,...,Direct,0,0,C,C,No Deposit,0,Transient,107.0,Check-Out
7,Resort Hotel,0,9,2015,July,1,0,2,2,0,...,Direct,0,0,C,C,No Deposit,0,Transient,103.0,Check-Out
8,Resort Hotel,1,85,2015,July,1,0,3,2,0,...,Online TA,0,0,A,A,No Deposit,0,Transient,82.0,Canceled
9,Resort Hotel,1,75,2015,July,1,0,3,2,0,...,Offline TA/TO,0,0,D,D,No Deposit,0,Transient,105.5,Canceled

In [42]:
df = df.dropna(subset=['country'])
display(df.head(10))

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,market_segment,is_repeated_guest,previous_cancellations,reserved_room_type,assigned_room_type,deposit_type,days_in_waiting_list,customer_type,adr,reservation_status
0,Resort Hotel,0,342,2015,July,1,0,0,2,0,...,Direct,0,0,C,C,No Deposit,0,Transient,0.0,Check-Out
1,Resort Hotel,0,737,2015,July,1,0,0,2,0,...,Direct,0,0,C,C,No Deposit,0,Transient,0.0,Check-Out
2,Resort Hotel,0,7,2015,July,1,0,1,1,0,...,Direct,0,0,A,C,No Deposit,0,Transient,75.0,Check-Out
3,Resort Hotel,0,13,2015,July,1,0,1,1,0,...,Corporate,0,0,A,A,No Deposit,0,Transient,75.0,Check-Out
4,Resort Hotel,0,14,2015,July,1,0,2,2,0,...,Online TA,0,0,A,A,No Deposit,0,Transient,98.0,Check-Out
5,Resort Hotel,0,14,2015,July,1,0,2,2,0,...,Online TA,0,0,A,A,No Deposit,0,Transient,98.0,Check-Out
6,Resort Hotel,0,0,2015,July,1,0,2,2,0,...,Direct,0,0,C,C,No Deposit,0,Transient,107.0,Check-Out
7,Resort Hotel,0,9,2015,July,1,0,2,2,0,...,Direct,0,0,C,C,No Deposit,0,Transient,103.0,Check-Out
8,Resort Hotel,1,85,2015,July,1,0,3,2,0,...,Online TA,0,0,A,A,No Deposit,0,Transient,82.0,Canceled
9,Resort Hotel,1,75,2015,July,1,0,3,2,0,...,Offline TA/TO,0,0,D,D,No Deposit,0,Transient,105.5,Canceled

MENAMBAHKAN KOLOM UNTUK KATEGORI LAMA DURASI RESERVASI

In [54]:
if 'lead_time' in df.columns:
    df['lead_time_category'] = pd.cut(df['lead_time'], bins=[0, 7, 30, 90, float('inf')], labels=['Last Minute', 'Short Term', 'Medium Term', 'Long Term'])
    display(df)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,previous_cancellations,reserved_room_type,assigned_room_type,deposit_type,days_in_waiting_list,customer_type,adr,reservation_status,lead_time_category,stay_duration
0,Resort Hotel,0,342,2015,July,1,0,0,2,0,...,0,C,C,No Deposit,0,Transient,0.00,Check-Out,Long Term,0
1,Resort Hotel,0,737,2015,July,1,0,0,2,0,...,0,C,C,No Deposit,0,Transient,0.00,Check-Out,Long Term,0
2,Resort Hotel,0,7,2015,July,1,0,1,1,0,...,0,A,C,No Deposit,0,Transient,75.00,Check-Out,Last Minute,1
3,Resort Hotel,0,13,2015,July,1,0,1,1,0,...,0,A,A,No Deposit,0,Transient,75.00,Check-Out,Short Term,1
4,Resort Hotel,0,14,2015,July,1,0,2,2,0,...,0,A,A,No Deposit,0,Transient,98.00,Check-Out,Short Term,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,30,2,5,2,0,...,0,A,A,No Deposit,0,Transient,96.14,Check-Out,Short Term,7
119386,City Hotel,0,102,2017,August,31,2,5,3,0,...,0,E,E,No Deposit,0,Transient,225.43,Check-Out,Long Term,7
119387,City Hotel,0,34,2017,August,31,2,5,2,0,...,0,D,D,No Deposit,0,Transient,157.71,Check-Out,Medium Term,7
119388,City Hotel,0,109,2017,August,31,2,5,2,0,...,0,A,A,No Deposit,0,Transient,104.40,Check-Out,Long Term,7
119389,City Hotel,0,205,2017,August,29,2,7,2,0,...,0,A,A,No Deposit,0,Transient,151.20,Check-Out,Long Term,9

MENAMBAHKAN KOLOM UNTUK DURASI MENGINAP

In [55]:
if 'stays_in_weekend_nights' in df.columns and 'stays_in_week_nights' in df.columns:
    df['stay_duration'] = df['stays_in_weekend_nights'] + df['stays_in_week_nights']
    display(df)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,previous_cancellations,reserved_room_type,assigned_room_type,deposit_type,days_in_waiting_list,customer_type,adr,reservation_status,lead_time_category,stay_duration
0,Resort Hotel,0,342,2015,July,1,0,0,2,0,...,0,C,C,No Deposit,0,Transient,0.00,Check-Out,Long Term,0
1,Resort Hotel,0,737,2015,July,1,0,0,2,0,...,0,C,C,No Deposit,0,Transient,0.00,Check-Out,Long Term,0
2,Resort Hotel,0,7,2015,July,1,0,1,1,0,...,0,A,C,No Deposit,0,Transient,75.00,Check-Out,Last Minute,1
3,Resort Hotel,0,13,2015,July,1,0,1,1,0,...,0,A,A,No Deposit,0,Transient,75.00,Check-Out,Short Term,1
4,Resort Hotel,0,14,2015,July,1,0,2,2,0,...,0,A,A,No Deposit,0,Transient,98.00,Check-Out,Short Term,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,30,2,5,2,0,...,0,A,A,No Deposit,0,Transient,96.14,Check-Out,Short Term,7
119386,City Hotel,0,102,2017,August,31,2,5,3,0,...,0,E,E,No Deposit,0,Transient,225.43,Check-Out,Long Term,7
119387,City Hotel,0,34,2017,August,31,2,5,2,0,...,0,D,D,No Deposit,0,Transient,157.71,Check-Out,Medium Term,7
119388,City Hotel,0,109,2017,August,31,2,5,2,0,...,0,A,A,No Deposit,0,Transient,104.40,Check-Out,Long Term,7
119389,City Hotel,0,205,2017,August,29,2,7,2,0,...,0,A,A,No Deposit,0,Transient,151.20,Check-Out,Long Term,9