In [6]:
import pandas as pd

# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)

# pd.reset_option('display.max_rows')
# pd.reset_option('display.max_columns')

In [7]:
df = pd.read_csv('hotel_bookings.csv')
df.head(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.0,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.0,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.5,0,0,Canceled,2015-04-22

In [8]:
# df.shape[0]

In [9]:
# df.info()

# Data Cleaning for Hotel Bookings

## 1. Kolom yang Dihapus
Beberapa kolom tidak relevan atau tidak digunakan dalam analisis ini, sehingga akan dihapus untuk menyederhanakan dataset:

- **arrival_date_week_number**: Kolom ini dihapus karena tanggal kedatangan sudah diketahui dari kolom lain.
- **distribution_channel**: Kolom ini dihapus karena `market_segment` memberikan detail yang lebih tentang user yang memesan.
- **previous_bookings_not_canceled**: Tidak digunakan dalam analisis.
- **booking_changes**: Tidak digunakan dalam analisis.
- **agent**: Kolom ini dihapus karena terlalu banyak nilai null.
- **company**: Dihapus karena terlalu banyak data null.
- **required_car_parking_spaces**: Tidak digunakan untuk analisis.
- **total_of_special_requests**: Tidak digunakan untuk analisis.
- **reservation_status_date**: Dihapus karena tanggal reservasi sudah dapat diketahui dari kolom lain seperti `arrival_date_year`, `arrival_date_month`, dan `arrival_date_day_of_month`.

## 2. Gabungkan Kolom `children` dan `babies`
Dikarenakan pemesanan hotel hanya melibatkan opsi dewasa dan anak-anak, maka kolom `children` dan `babies` akan digabung menjadi satu kolom baru dengan nama `children`. Nilai null pada kolom ini akan diisi dengan 0.

## 3. Hapus Baris Berdasarkan Kondisi
### Baris dengan `previous_cancellations` > 0
Baris dengan nilai pada kolom `previous_cancellations` lebih dari 0 akan dihapus untuk menghindari duplikasi data.

### Baris dengan `days_in_waiting_list` > 31
Kolom ini merepresentasikan lamanya waktu menunggu dalam daftar tunggu. Data yang menunjukkan waktu tunggu lebih dari satu bulan (> 31 hari) akan dihapus karena dianggap tidak realistis.

## 4. Hapus Baris Null pada Kolom `country`
Beberapa baris pada kolom `country` memiliki nilai null. Karena jumlahnya sedikit, baris ini akan dihapus karena tidak terlalu mempengaruhi analisis secara keseluruhan.

---

Langkah-langkah pembersihan data ini akan menghasilkan dataset yang lebih rapi dan relevan untuk analisis lebih lanjut.

In [10]:
kolom_dihapus = ['arrival_date_week_number', 'distribution_channel', 'previous_bookings_not_canceled', 'booking_changes',
                 'agent', 'company', 'required_car_parking_spaces', 'total_of_special_requests', 'reservation_status_date']
df.drop(columns=kolom_dihapus, inplace=True, errors='ignore')
print("Setelah menghapus kolom tidak relevan:")
display(df)

Setelah menghapus kolom tidak relevan:

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,market_segment,is_repeated_guest,previous_cancellations,reserved_room_type,assigned_room_type,deposit_type,days_in_waiting_list,customer_type,adr,reservation_status
0,Resort Hotel,0,342,2015,July,1,0,0,2,0.0,...,Direct,0,0,C,C,No Deposit,0,Transient,0.00,Check-Out
1,Resort Hotel,0,737,2015,July,1,0,0,2,0.0,...,Direct,0,0,C,C,No Deposit,0,Transient,0.00,Check-Out
2,Resort Hotel,0,7,2015,July,1,0,1,1,0.0,...,Direct,0,0,A,C,No Deposit,0,Transient,75.00,Check-Out
3,Resort Hotel,0,13,2015,July,1,0,1,1,0.0,...,Corporate,0,0,A,A,No Deposit,0,Transient,75.00,Check-Out
4,Resort Hotel,0,14,2015,July,1,0,2,2,0.0,...,Online TA,0,0,A,A,No Deposit,0,Transient,98.00,Check-Out
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,30,2,5,2,0.0,...,Offline TA/TO,0,0,A,A,No Deposit,0,Transient,96.14,Check-Out
119386,City Hotel,0,102,2017,August,31,2,5,3,0.0,...,Online TA,0,0,E,E,No Deposit,0,Transient,225.43,Check-Out
119387,City Hotel,0,34,2017,August,31,2,5,2,0.0,...,Online TA,0,0,D,D,No Deposit,0,Transient,157.71,Check-Out
119388,City Hotel,0,109,2017,August,31,2,5,2,0.0,...,Online TA,0,0,A,A,No Deposit,0,Transient,104.40,Check-Out
119389,City Hotel,0,205,2017,August,29,2,7,2,0.0,...,Online TA,0,0,A,A,No Deposit,0,Transient,151.20,Check-Out

In [ ]:
# missing_values_rows = df[df.isnull().any(axis=1)]
# missing_values_rows = df[df['agent'].isnull()]
# missing_values_rows.head()
# unique_values = df['babies'].value_counts().sort_index()
# unique_values