# Take Home Assignment - E-commerce Website Performance Analysis

---

## E-commerce Website Performance Analysis

You are an analyst working for a thriving e-commerce company called "Tech Haven." Tech Haven sells a wide range of technology products online, including
smartphones, laptops, accessories, and more. The company operates its online store and is keen on understanding its monthly performance to make informed
decisions.

***Data Description***

- **Visitors:** The number of visitors to the Tech Haven website each month. This metric represents the traffic the website receives.
- **Revenue:** The monthly revenue generated from the sales of products on the website, measured in thousands of dollars. It includes revenue from product sales
and any additional services offered.
- **Expenses**: Monthly operating expenses incurred by Tech Haven, including marketing, server costs, employee salaries, and other business-related costs. Also
measured in thousands of dollars.

***Business Tasks:***

1. **Conversion Rate Analysis**: Tech Haven is interested in understanding how well it is converting website visitors into paying customers. The conversion rate,
which is calculated as the ratio of revenue to the number of visitors, is a crucial metric for this analysis.
2. **Growth Analysis**: The company wants to assess its month-over-month and cumulative growth in terms of website visitors and revenue. Positive growth is an
indicator of a healthy business.
3. **Profit Calculation**: Tech Haven wants to calculate its monthly profit, which is the difference between revenue and expenses. Understanding profitability is
essential for financial planning.
4. **High-Performance Months**: The company is looking to identify months with high conversion rates, profits, and net profits. These months could provide insights
into what contributes to success.
5. **Average Profit Analysis**: Tech Haven wants to know the average monthly profit over the year to get a sense of the consistent performance.
6. **Correlation Analysis**: The correlation between website visitors and revenue is of interest to assess whether there's a relationship between traffic and sales.
7. **Tax and Net Profit Analysis**: The company wants to factor in tax expenses and calculate the net profit for each month, which provides a more accurate picture
of profitability.
8. **Moving Average Analysis**: Understanding trends in revenue is crucial. Calculating a 3-month moving average helps in smoothing out fluctuations and
identifying trends.

***Key Business Decisions:***

1. Understanding which months had the highest conversion rates can help in optimizing marketing efforts during similar periods.
2. Identifying months with high profits and net profits can guide resource allocation and investment decisions.
3. Analyzing correlations can help in predicting future revenue based on website traffic.
Monitoring growth rates helps in setting realistic business goals.
4. Tracking moving averages can provide insights into long-term performance trends.

In [26]:
import numpy as np
import pandas as pd

# Monthly data for the e-commerce website
visitors = np.array([1000, 1200, 1100, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100])
revenue = np.array([20000, 22000, 21000, 23000, 24000, 25000, 26000, 27000, 28000, 29000, 30000, 31000])
expenses = np.array([15000, 16000, 15500, 16500, 17000, 17500, 18000, 18500, 19000, 19500, 20000, 20500])

In [27]:
# Monthly data for the e-commerce website
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
visitors = np.array([1000, 1200, 1100, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100])
revenue = np.array([20000, 22000, 21000, 23000, 24000, 25000, 26000, 27000, 28000, 29000, 30000, 31000])
expenses = np.array([15000, 16000, 15500, 16500, 17000, 17500, 18000, 18500, 19000, 19500, 20000, 20500])

# 1. Conversion Rate
conversion_rate = (revenue / visitors) * 100

# 2. Month-over-Month Growth
mom_growth_visitors = np.concatenate(([np.nan], np.diff(visitors) / visitors[:-1] * 100))  # prepend NaN for the first month
mom_growth_revenue = np.concatenate(([np.nan], np.diff(revenue) / revenue[:-1] * 100))  # prepend NaN for the first month

# 3. Monthly Profit
profit = revenue - expenses

# 4. High-Performance Months (we'll identify these later)

# 5. Average Monthly Profit (this will be a constant value)
average_profit = np.mean(profit)

# 6. Correlation between Visitors and Revenue
correlation = np.corrcoef(visitors, revenue)[0, 1]

# 7. Tax and Net Profit (20% tax rate)
tax_rate = 0.20
tax = profit * tax_rate
net_profit = profit - tax

# 8. 3-Month Moving Average for Revenue
moving_average_revenue = np.concatenate((np.full(2, np.nan), np.convolve(revenue, np.ones(3)/3, mode='valid')))  # prepend NaN for first two months

# Create a DataFrame
df = pd.DataFrame({
    'Month': months,
    'Visitors': visitors,
    'Revenue': revenue,
    'Expenses': expenses,
    'Profit': profit,
    'Net Profit': net_profit,
    'Conversion Rate (%)': conversion_rate,
    'MoM Growth (Visitors %)': mom_growth_visitors,
    'MoM Growth (Revenue %)': mom_growth_revenue,
    '3-Month Moving Avg (Revenue)': moving_average_revenue
})

# Output the DataFrame
df.index = df.index + 1  # Adjust index to start from 1 for readability

# Additional outputs
print("\nAverage Monthly Profit: ", average_profit)
print("Correlation between Visitors and Revenue: ", correlation)

Average Monthly Profit:  7750.0
Correlation between Visitors and Revenue:  1.0

In [28]:
df

,Month,Visitors,Revenue,Expenses,Profit,Net Profit,Conversion Rate (%),MoM Growth (Visitors %),MoM Growth (Revenue %),3-Month Moving Avg (Revenue)
1,Jan,1000,20000,15000,5000,4000.0,2000.000000,NaN,NaN,NaN
2,Feb,1200,22000,16000,6000,4800.0,1833.333333,20.000000,10.000000,NaN
3,Mar,1100,21000,15500,5500,4400.0,1909.090909,-8.333333,-4.545455,21000.000000
4,Apr,1300,23000,16500,6500,5200.0,1769.230769,18.181818,9.523810,22000.000000
5,May,1400,24000,17000,7000,5600.0,1714.285714,7.692308,4.347826,22666.666667
6,Jun,1500,25000,17500,7500,6000.0,1666.666667,7.142857,4.166667,24000.000000
7,Jul,1600,26000,18000,8000,6400.0,1625.000000,6.666667,4.000000,25000.000000
8,Aug,1700,27000,18500,8500,6800.0,1588.235294,6.250000,3.846154,26000.000000
9,Sep,1800,28000,19000,9000,7200.0,1555.555556,5.882353,3.703704,27000.000000
10,Oct,1900,29000,19500,9500,7600.0,1526.315789,5.555556,3.571429,28000.000000
11,Nov,2000,30000,20000,10000,8000.0,1500.000000,5.263158,3.448276,29000.000000
12,Dec,2100,31000,20500,10500,8400.0,1476.190476,5.000000,3.333333,30000.000000